### ISSUE TITLE
"technologies" cards misaligned

### ISSUE THREAD

**Issue by choccymilku** [whosneksio/web#1]
# before fix
![image](https://github.com/whosneksio/web/assets/99021003/559d337b-9a82-4392-bf6e-c5fcf544c1fa)

the fix is simple, just remove `left: 40px` in `.tech-card-desc`

![image](https://github.com/whosneksio/web/assets/99021003/f2da9a69-1ffb-43f5-b992-70f30d4a59e1)
# after fix
![image](https://github.com/whosneksio/web/assets/99021003/de13361a-1090-4ad4-b7f4-fab17efad759)

**Comment by whosneksio** [comment]
thank you so much sir
